LOGIN_URL = "https://interview.supporthive.com/staff/login"
USERNAME = "Agent"
PASSWORD = "Agent@123"
STATUS_NAME = "Issue Created"
STATUS_COLOR = "#47963f"
PRIORITY_NAME = "Assistance required"
PRIORITY_DESCRIPTION = "Priority of the newly created tickets"
